"""Stable, data-driven expectations used by the release validator."""

REQUIRED_PATHS = (
    'README.md',
    'DarkOneJSP3/build-info.json',
    'DarkOneJSP3/darkonejsp3-layout-manifest.json',
    'DarkOneJSP3/images/QS.bmp',
    'DarkOneJSP3/images/buttons.png',
    'DarkOneJSP3/images/dot_matrix.png',
    'DarkOneJSP3/images/sac_pbo.png',
    'DarkOneJSP3/shared/reset_defaults.js',
    'DarkOneJSP3/shared/performance_utils.js',
    'DarkOneJSP3/shared/ui_cadence.js',
    'DarkOneJSP3/shared/colour_utils.js',
    'DarkOneJSP3/shared/jsplitter_protocols.js',
    'DarkOneJSP3/jsplitter/shared.js',
    'DarkOneJSP3/jsplitter/01_root.js',
    'DarkOneJSP3/jsplitter/02_main_columns.js',
    'DarkOneJSP3/jsplitter/03_info_stack_tabs.js',
    'DarkOneJSP3/jsplitter/04_art_spectrum.js',
    'DarkOneJSP3/jsplitter/05_bottom_controls.js',
    'DarkOneJSP3/jsplitter/06_display_waveform.js',
    'DarkOneJSP3/jsplitter/info_stack_colours.js',
    'DarkOneJSP3/jsplitter/info_stack_bridges.js',
    'DarkOneJSP3/jsplitter/loaders/JSplitter 01 - Root.txt',
    'DarkOneJSP3/jsplitter/loaders/JSplitter 02 - Main Columns.txt',
    'DarkOneJSP3/jsplitter/loaders/JSplitter 03 - Info Stack and Tabs.txt',
    'DarkOneJSP3/jsplitter/loaders/JSplitter 04 - Album Art and Spectrum.txt',
    'DarkOneJSP3/jsplitter/loaders/JSplitter 05 - Bottom Controls.txt',
    'DarkOneJSP3/jsplitter/loaders/JSplitter 06 - Display and Waveform.txt',
    'DarkOneJSP3/jscript/DarkOneJSP3 - Control Panel - Left.txt',
    'DarkOneJSP3/jscript/DarkOneJSP3 - Control Panel - Right.txt',
    'DarkOneJSP3/jscript/DarkOneJSP3 - Display Panel.txt',
    'DarkOneJSP3/jscript/DarkOneJSP3 - Queue Viewer.txt',
    'DarkOneJSP3/jscript/js/Buttons_OptionalMenu.js',
    'DarkOneJSP3/jscript/js/Queue_Viewer.js',
    'DarkOneJSP3/docs/README.txt',
    'DarkOneJSP3/docs/INSTALLATION.txt',
    'DarkOneJSP3/docs/LAYOUT_AND_PANEL_MAP.txt',
    'DarkOneJSP3/docs/CONFIGURATION_GUIDE.txt',
    'DarkOneJSP3/docs/TROUBLESHOOTING.txt',
    'DarkOneJSP3/docs/MIGRATION_REFERENCE.txt',
    'DarkOneJSP3/docs/CHANGELOG.txt',
    'DarkOneJSP3/docs/CREDITS.txt',
    'DarkOneJSP3/docs/VALIDATION_REPORT.txt',
    'DarkOneJSP3/docs/ENHANCED_SAMPLES.txt',
    'DarkOneJSP3/tools/sync_mirrors.py',
    'DarkOneJSP3/tools/validation/__init__.py',
    'DarkOneJSP3/tools/validation/context.py',
    'DarkOneJSP3/tools/validation/expectations.py',
    'DarkOneJSP3/tools/validation/static_checks.py',
    'DarkOneJSP3/tools/validation/runtime_checks.py',
    'user-components-x64/foo_jscript_panel3/helpers.txt',
    'user-components-x64/foo_jscript_panel3/samples/README.md',
    'user-components-x64/foo_jscript_panel3/samples/Album Notes.txt',
    'user-components-x64/foo_jscript_panel3/samples/Album Art.txt',
    'user-components-x64/foo_jscript_panel3/samples/Last.fm Bio.txt',
    'user-components-x64/foo_jscript_panel3/samples/Last.fm Artist Info + User Info.txt',
    'user-components-x64/foo_jscript_panel3/samples/MusicBrainz.txt',
    'user-components-x64/foo_jscript_panel3/samples/JS Playlist.txt',
    'user-components-x64/foo_jscript_panel3/samples/Properties.txt',
    'user-components-x64/foo_jscript_panel3/samples/Smooth Playlist Manager.txt',
    'user-components-x64/foo_jscript_panel3/samples/images/foobar2000.png',
    'user-components-x64/foo_jscript_panel3/samples/js/common.js',
    'user-components-x64/foo_jscript_panel3/samples/js/jsp3_enhanced_reset.js',
    'user-components-x64/foo_jscript_panel3/samples/js/darkonejsp3_reset.js',
    'user-components-x64/foo_jscript_panel3/samples/js/darkone_network.js',
    'user-components-x64/foo_jscript_panel3/samples/js/allmusic.js',
    'user-components-x64/foo_jscript_panel3/samples/js/album_notes.js',
    'user-components-x64/foo_jscript_panel3/samples/js/musicbrainz.js',
    'user-components-x64/foo_jscript_panel3/samples/js/panel.js',
    'user-components-x64/foo_jscript_panel3/samples/js/queue_viewer.js',
    'user-components-x64/foo_jscript_panel3/samples/jsplaylist/render_cache.js',
    'user-components-x64/foo_jscript_panel3/samples/shared/sample_defaults.js',
    'user-components-x64/foo_jscript_panel3/samples/shared/performance_utils.js',
    'user-components-x64/foo_jscript_panel3/samples/shared/ui_cadence.js',
    'user-components-x64/foo_jscript_panel3/samples/shared/colour_utils.js',
)

EXPECTED_MODULE_VERSIONS = {
    'control_left': ('3.0.13-jsp3-3.8.5', 'Control Left'),
    'control_right': ('3.0.18-jsp3-3.8.5', 'Control Right'),
    'display': ('3.0.16-jsp3-3.8.5', 'Display'),
    'queue_viewer': ('0.6.1', 'Queue Viewer'),
    'allmusic': ('0.6.4', 'AllMusic'),
    'musicbrainz': ('0.6.4', 'MusicBrainz'),
    'js_playlist': ('0.6.0', 'JS Playlist'),
    'playlist_manager': ('0.5.5', 'Playlist Manager'),
    'network_headers': ('0.6.2', 'network-header identity'),
    'album_notes': ('0.6.8', 'Album Notes'),
    'info_stack_controller': ('0.6.25', 'InfoStack controller'),
    'startup_controller': ('0.7.36', 'startup controller'),
    'main_columns_controller': ('0.7.36', 'Main Columns controller'),
    'page_background': ('0.1.3', 'page-background module'),
    'colour_helpers': ('0.1.0', 'colour-helper module'),
    'performance_helpers': ('0.1.4', 'performance-helper module'),
    'ui_cadence': ('0.1.1', 'UI-cadence protocol module'),
    'playlist_render_cache': ('0.1.0', 'playlist render-cache module'),
    'jsplitter_protocols': ('0.1.0', 'JSplitter-protocol module'),
    'optional_button_menu': ('0.1.0', 'optional-button menu module'),
    'info_stack_colours': ('0.1.0', 'InfoStack colour helper'),
    'info_stack_bridges': ('0.1.0', 'InfoStack bridge helper'),
    'release_validator': ('0.4.7', 'release-validator module'),
    'sample_defaults': ('0.1.0', 'standalone sample-default registry'),
    'sample_reset_bridge': ('0.1.1', 'standalone sample reset bridge'),
    'standalone_sample_compatibility': ('0.1.1', 'legacy sample-entry compatibility layer'),
}

SEMVER_MODULES = ()


# Principal menu labels whose source and documentation must remain aligned.
# These are deliberately representative rather than a complete parser of the
# host APIs: a missing source label catches a renamed menu, while a missing
# guide label catches documentation drift.
MENU_DOCUMENTATION_EXPECTATIONS = (
    {
        'name': 'shared JScript Panel page controls',
        'source': 'user-components-x64/foo_jscript_panel3/samples/js/panel.js',
        'labels': (
            'Font size',
            'Page background colour',
            'Selection mode',
            'Configure...',
        ),
    },
    {
        'name': 'Playlist Manager settings',
        'source': 'user-components-x64/foo_jscript_panel3/samples/smooth/jsspm.js',
        'labels': (
            'Header Bar',
            'Playlist filter',
            'Alternating row shading',
            'Background Wallpaper',
            'Enhanced smooth scrolling',
            'Remember manager scroll position',
            'Keep active playlist visible',
            'Set custom refresh interval...',
            'Playlist row spacing',
            'Original JSP3 spacing (32)',
            'Configure...',
        ),
    },
    {
        'name': 'JS Playlist context menu',
        'source': 'user-components-x64/foo_jscript_panel3/samples/jsplaylist/playlist.js',
        'labels': (
            'Panel Settings...',
            'Enable Dynamic',
            'Enable Custom',
            'Smooth scrolling',
            'Snap wheel scrolling to playlist rows',
            'Set free-scroll wheel distance...',
            'Snap scrollbar dragging to playlist rows',
            'Restore enhanced defaults',
        ),
    },
    {
        'name': 'JS Playlist header menu',
        'source': 'user-components-x64/foo_jscript_panel3/samples/jsplaylist/headerbar.js',
        'labels': (
            'Enable Groups',
            'Double Track Line',
        ),
    },
    {
        'name': 'JS Playlist Panel Settings',
        'source': 'user-components-x64/foo_jscript_panel3/samples/jsplaylist/settings.js',
        'labels': (
            'Show Information Panel (toggle = CTRL+I)',
            'Show Header Toolbar (toggle = CTRL+T)',
            'Extra Line Title Format',
            'Enable Cover',
            'Default Wallpaper Path',
        ),
    },
    {
        'name': 'Biography menu',
        'source': 'user-components-x64/foo_jscript_panel3/samples/js/lastfm_bio.js',
        'labels': (
            'Force update',
            'Last.fm API key...',
            'Last.fm language',
            'Country flags',
            'Show extra info',
            'Open containing folder',
        ),
    },
    {
        'name': 'Last.fm menu',
        'source': 'user-components-x64/foo_jscript_panel3/samples/js/lastfm_info.js',
        'labels': (
            'Artist Info',
            'User Info',
            'Similar Artists',
            'Top Tracks',
            'Top Tags',
            'Recent Tracks',
            'Last.fm username...',
        ),
    },
    {
        'name': 'Properties menu',
        'source': 'user-components-x64/foo_jscript_panel3/samples/js/properties.js',
        'labels': (
            'Metadata',
            'Location',
            'Tech Info',
            'Open containing folder',
        ),
    },
    {
        'name': 'Album Art menu',
        'source': 'user-components-x64/foo_jscript_panel3/samples/js/albumart.js',
        'labels': (
            'Refresh',
            'Crop (focus on centre)',
            'Crop (focus on top)',
            'Show hover tooltip',
            'Google image search',
            'Double click',
        ),
    },
    {
        'name': 'InfoStack menu',
        'source': 'DarkOneJSP3/jsplitter/03_info_stack_tabs.js',
        'labels': (
            'Select tab',
            'Visible tabs',
            'Tab titles',
            'Tab font size',
            'Tab font colour',
            'Tab area',
            'InfoStack backing colour',
            'Side divider colour',
            'Startup',
        ),
    },
    {
        'name': 'Waveform host menu',
        'source': 'DarkOneJSP3/jsplitter/06_display_waveform.js',
        'labels': (
            'Host background',
            'Force blank waveform when playback stops',
            'New-track reveal delay',
            'Reset waveform-area settings',
        ),
    },
    {
        'name': 'volume-knob menu',
        'source': 'DarkOneJSP3/jscript/js/Object_Volumeknob.js',
        'labels': (
            'Volume drag refresh rate',
        ),
    },
    {
        'name': 'Display menu',
        'source': 'DarkOneJSP3/jscript/js/Panel_Display.js',
        'labels': (
            'Plain Font',
            'Dot Matrix',
            'Display Style',
            'Display accent colour',
            'DarkOne Tools...',
        ),
    },
    {
        'name': 'optional control-button menu',
        'source': 'DarkOneJSP3/jscript/js/Buttons_OptionalMenu.js',
        'labels': (
            'Optional buttons',
            'DarkOne Tools...',
            'Button roundness',
        ),
    },
    {
        'name': 'DarkOne Tools menu',
        'source': 'DarkOneJSP3/jscript/js/Config_Global_Script.js',
        'labels': (
            'Fonts',
            'High-DPI / scaling',
            'Reset DarkOneJSP3',
            'Control font scale...',
            'Button hitbox scale...',
            'Reset all font defaults',
            'Panel properties',
            'Configure script...',
            'Reload this panel',
        ),
    },
    {
        'name': 'left control appearance menu',
        'source': 'DarkOneJSP3/jscript/js/Panel_Control_Left.js',
        'labels': (
            'Button style',
            'Button depth',
            'Preset ',
            'Flat',
            'Soft',
            'Medium',
            'Strong',
        ),
    },
    {
        'name': 'volume knob menu',
        'source': 'DarkOneJSP3/jscript/js/Object_Volumeknob.js',
        'labels': (
            'Up',
            'Down',
            'Volume Mute',
        ),
    },
    {
        'name': 'startup menu',
        'source': 'DarkOneJSP3/jsplitter/info_stack_bridges.js',
        'labels': (
            'Off',
            'Black reveal',
            'Staged reveal',
            'Transition',
            'Minimum black hold',
            'Layout-readiness timeout',
            'Preview startup transition',
            'Restore startup defaults',
        ),
    },
    {
        'name': 'Playlist Manager row menu',
        'source': 'user-components-x64/foo_jscript_panel3/samples/smooth/jsspm.js',
        'labels': (
            'Rename this playlist',
            'Remove this playlist',
            'Duplicate this playlist',
            'Create new playlist',
            'Load playlist...',
            'Create new autoplaylist',
            'Preset autoplaylists',
            'Clear history',
            'Sort playlists A-Z',
        ),
    },
    {
        'name': 'AllMusic menu',
        'source': 'user-components-x64/foo_jscript_panel3/samples/js/allmusic.js',
        'labels': (
            'Paste review from clipboard',
            'Open album on AllMusic',
            'Refresh from AllMusic (retry once)',
            'Delete cached review',
            'Fetch from manual AllMusic URL...',
            'Copy AllMusic album URL',
            'AllMusic cache/tools',
        ),
    },
    {
        'name': 'MusicBrainz menu',
        'source': 'user-components-x64/foo_jscript_panel3/samples/js/musicbrainz.js',
        'labels': (
            'Track artist',
            'Album artist',
            'Automatically resolve missing artist IDs',
            'Resolve current artist now',
            'Set artist MBID manually...',
            'Release limit',
            'Release sorting',
            'Show full link URLs',
            'Remember scroll position',
            'Set MusicBrainz contact URL/email...',
        ),
    },
    {
        'name': 'Album Notes menu',
        'source': 'user-components-x64/foo_jscript_panel3/samples/js/album_notes.js',
        'labels': (
            'Album notes',
            'MusicBrainz releases',
            'MusicBrainz links',
            'Best available',
            'Browse one source',
            'MusicBrainz matching and relationships',
            'Restore default order',
            'Prefer descriptive sources',
            'Refresh enabled sources',
            'Clear current source cache',
            'Show diagnostics',
            'Copy displayed notes',
        ),
    },
    {
        'name': 'scripted Queue Viewer menu',
        'source': 'DarkOneJSP3/jscript/js/Queue_Viewer.js',
        'labels': (
            'Show source playlist item',
            'Play source item now',
            'Open containing folder',
            'Copy item title',
            'Copy file path',
            'Item display title formatting...',
            'Re-scan playback queue',
        ),
    },
)
