"""Stable, data-driven expectations used by the release validator."""

REQUIRED_PATHS = (
    'README.md',
    'DarkOneJSP3/build-info.json',
    'DarkOneJSP3/darkonejsp3-layout-manifest.json',
    'DarkOneJSP3/shared/reset_defaults.js',
    'DarkOneJSP3/shared/colour_utils.js',
    'DarkOneJSP3/shared/jsplitter_protocols.js',
    'DarkOneJSP3/jsplitter/info_stack_colours.js',
    'DarkOneJSP3/jsplitter/info_stack_bridges.js',
    'DarkOneJSP3/jscript/js/Buttons_OptionalMenu.js',
    'DarkOneJSP3/jsplitter/shared.js',
    'DarkOneJSP3/docs/README.txt',
    'DarkOneJSP3/docs/INSTALLATION.txt',
    'DarkOneJSP3/docs/LAYOUT_AND_PANEL_MAP.txt',
    'DarkOneJSP3/docs/CONFIGURATION_GUIDE.txt',
    'DarkOneJSP3/docs/TROUBLESHOOTING.txt',
    'DarkOneJSP3/docs/CHANGELOG.txt',
    'DarkOneJSP3/docs/CREDITS.txt',
    'DarkOneJSP3/docs/VALIDATION_REPORT.txt',
    'DarkOneJSP3/tools/validation/__init__.py',
    'DarkOneJSP3/tools/validation/context.py',
    'DarkOneJSP3/tools/validation/expectations.py',
    'DarkOneJSP3/tools/validation/static_checks.py',
    'DarkOneJSP3/tools/validation/runtime_checks.py',
    'user-components-x64/foo_jscript_panel3/samples/Album Notes.txt',
    'user-components-x64/foo_jscript_panel3/samples/Album Art.txt',
    'user-components-x64/foo_jscript_panel3/samples/MusicBrainz.txt',
    'user-components-x64/foo_jscript_panel3/samples/JS Playlist.txt',
    'user-components-x64/foo_jscript_panel3/samples/Smooth Playlist Manager.txt',
    'user-components-x64/foo_jscript_panel3/samples/js/common.js',
    'user-components-x64/foo_jscript_panel3/samples/js/darkonejsp3_reset.js',
    'user-components-x64/foo_jscript_panel3/samples/js/allmusic.js',
    'user-components-x64/foo_jscript_panel3/samples/js/album_notes.js',
)

EXPECTED_MODULE_VERSIONS = {
    'allmusic': ('0.6.4', 'AllMusic'),
    'album_notes': ('0.6.7', 'Album Notes'),
    'js_playlist': ('0.4.7', 'JS Playlist'),
    'info_stack_controller': ('0.6.25', 'InfoStack controller'),
    'info_stack_colours': ('0.1.0', 'InfoStack colour helper'),
    'info_stack_bridges': ('0.1.0', 'InfoStack bridge helper'),
    'display': ('3.0.11-jsp3-3.8.5', 'Display module'),
    'queue_viewer': ('0.5.2', 'Queue Viewer'),
    'page_background': ('0.1.2', 'page-background module'),
    'colour_helpers': ('0.1.0', 'colour-helper module'),
    'jsplitter_protocols': ('0.1.0', 'JSplitter-protocol module'),
    'control_left': ('3.0.12-jsp3-3.8.5', 'Control Left module'),
    'control_right': ('3.0.12-jsp3-3.8.5', 'Control Right module'),
    'optional_button_menu': ('0.1.0', 'optional-button menu module'),
    'release_validator': ('0.2.0', 'release-validator module'),
}

SEMVER_MODULES = (
    'main_columns_controller',
    'startup_controller',
)
