"""Stable, data-driven expectations used by the release validator."""

REQUIRED_PATHS = (
    'README.md',
    'DarkOneJSP3/build-info.json',
    'DarkOneJSP3/darkonejsp3-layout-manifest.json',
    'DarkOneJSP3/images/QS.bmp',
    'DarkOneJSP3/images/buttons.png',
    'DarkOneJSP3/images/dot_matrix.png',
    'DarkOneJSP3/images/sac_pbo.png',
    'DarkOneJSP3/shared/reset_defaults.js',
    'DarkOneJSP3/shared/colour_utils.js',
    'DarkOneJSP3/shared/jsplitter_protocols.js',
    'DarkOneJSP3/jsplitter/shared.js',
    'DarkOneJSP3/jsplitter/01_root.js',
    'DarkOneJSP3/jsplitter/02_main_columns.js',
    'DarkOneJSP3/jsplitter/03_info_stack_tabs.js',
    'DarkOneJSP3/jsplitter/04_art_spectrum.js',
    'DarkOneJSP3/jsplitter/05_bottom_controls.js',
    'DarkOneJSP3/jsplitter/06_display_waveform.js',
    'DarkOneJSP3/jsplitter/info_stack_colours.js',
    'DarkOneJSP3/jsplitter/info_stack_bridges.js',
    'DarkOneJSP3/jsplitter/loaders/JSplitter 01 - Root.txt',
    'DarkOneJSP3/jsplitter/loaders/JSplitter 02 - Main Columns.txt',
    'DarkOneJSP3/jsplitter/loaders/JSplitter 03 - Info Stack and Tabs.txt',
    'DarkOneJSP3/jsplitter/loaders/JSplitter 04 - Album Art and Spectrum.txt',
    'DarkOneJSP3/jsplitter/loaders/JSplitter 05 - Bottom Controls.txt',
    'DarkOneJSP3/jsplitter/loaders/JSplitter 06 - Display and Waveform.txt',
    'DarkOneJSP3/jscript/DarkOneJSP3 - Control Panel - Left.txt',
    'DarkOneJSP3/jscript/DarkOneJSP3 - Control Panel - Right.txt',
    'DarkOneJSP3/jscript/DarkOneJSP3 - Display Panel.txt',
    'DarkOneJSP3/jscript/DarkOneJSP3 - Queue Viewer.txt',
    'DarkOneJSP3/jscript/js/Buttons_OptionalMenu.js',
    'DarkOneJSP3/jscript/js/Queue_Viewer.js',
    'DarkOneJSP3/docs/README.txt',
    'DarkOneJSP3/docs/INSTALLATION.txt',
    'DarkOneJSP3/docs/LAYOUT_AND_PANEL_MAP.txt',
    'DarkOneJSP3/docs/CONFIGURATION_GUIDE.txt',
    'DarkOneJSP3/docs/TROUBLESHOOTING.txt',
    'DarkOneJSP3/docs/MIGRATION_REFERENCE.txt',
    'DarkOneJSP3/docs/CHANGELOG.txt',
    'DarkOneJSP3/docs/CREDITS.txt',
    'DarkOneJSP3/docs/VALIDATION_REPORT.txt',
    'DarkOneJSP3/tools/sync_mirrors.py',
    'DarkOneJSP3/tools/validation/__init__.py',
    'DarkOneJSP3/tools/validation/context.py',
    'DarkOneJSP3/tools/validation/expectations.py',
    'DarkOneJSP3/tools/validation/static_checks.py',
    'DarkOneJSP3/tools/validation/runtime_checks.py',
    'user-components-x64/foo_jscript_panel3/helpers.txt',
    'user-components-x64/foo_jscript_panel3/samples/Album Notes.txt',
    'user-components-x64/foo_jscript_panel3/samples/Album Art.txt',
    'user-components-x64/foo_jscript_panel3/samples/Last.fm Bio.txt',
    'user-components-x64/foo_jscript_panel3/samples/Last.fm Artist Info + User Info.txt',
    'user-components-x64/foo_jscript_panel3/samples/MusicBrainz.txt',
    'user-components-x64/foo_jscript_panel3/samples/JS Playlist.txt',
    'user-components-x64/foo_jscript_panel3/samples/Properties.txt',
    'user-components-x64/foo_jscript_panel3/samples/Smooth Playlist Manager.txt',
    'user-components-x64/foo_jscript_panel3/samples/images/foobar2000.png',
    'user-components-x64/foo_jscript_panel3/samples/js/common.js',
    'user-components-x64/foo_jscript_panel3/samples/js/darkonejsp3_reset.js',
    'user-components-x64/foo_jscript_panel3/samples/js/darkone_network.js',
    'user-components-x64/foo_jscript_panel3/samples/js/allmusic.js',
    'user-components-x64/foo_jscript_panel3/samples/js/album_notes.js',
    'user-components-x64/foo_jscript_panel3/samples/js/musicbrainz.js',
    'user-components-x64/foo_jscript_panel3/samples/js/panel.js',
    'user-components-x64/foo_jscript_panel3/samples/js/queue_viewer.js',
)

EXPECTED_MODULE_VERSIONS = {
    'control_left': ('3.0.12-jsp3-3.8.5', 'Control Left'),
    'control_right': ('3.0.12-jsp3-3.8.5', 'Control Right'),
    'display': ('3.0.11-jsp3-3.8.5', 'Display'),
    'queue_viewer': ('0.5.2', 'Queue Viewer'),
    'allmusic': ('0.6.4', 'AllMusic'),
    'musicbrainz': ('0.6.3', 'MusicBrainz'),
    'js_playlist': ('0.4.7', 'JS Playlist'),
    'playlist_manager': ('0.4.10', 'Playlist Manager'),
    'network_headers': ('0.6.2', 'network-header identity'),
    'album_notes': ('0.6.7', 'Album Notes'),
    'info_stack_controller': ('0.6.25', 'InfoStack controller'),
    'startup_controller': ('0.7.36', 'startup controller'),
    'main_columns_controller': ('0.7.36', 'Main Columns controller'),
    'page_background': ('0.1.2', 'page-background module'),
    'colour_helpers': ('0.1.0', 'colour-helper module'),
    'jsplitter_protocols': ('0.1.0', 'JSplitter-protocol module'),
    'optional_button_menu': ('0.1.0', 'optional-button menu module'),
    'info_stack_colours': ('0.1.0', 'InfoStack colour helper'),
    'info_stack_bridges': ('0.1.0', 'InfoStack bridge helper'),
    'release_validator': ('0.2.1', 'release-validator module'),
}

SEMVER_MODULES = ()
